### ISSUE TITLE
Fails to recognize simple English words/phrases

### ISSUE THREAD

**Issue by ykessler** [peterc/whatlanguage#27]
Hi Peter- This project looks exciting, however we can't get the most basic tests working when trying simple English words or phrases:

require 'whatlanguage'
=> true 
"test".language
=> :dutch 
"hello".language
=> :arabic 
"how are you".language
=> :arabic

**Comment by forgottenleaf** [comment]
How about using unicode ranges to determine a string's language? (Obviously you wouldn't make a function for every language like this silly short example here)

```ruby
class String
  def arabic?
    index(/[\u0600-\u06FF]/) != nil
  end
end

puts 'اللغة التي هي هذه؟'.arabic? #=> true
puts 'You know that this is the body of the answer.'.arabic? #=> false
```

**Comment by subimage** [comment]
In the "comically bad" camp here. Was hopeful this would be useful on some article headlines for a project I'm working on but it seems like there is lots of work to do!

    I Puritani review – Bellini, gracefully poised in the Troubles
    - english

    PauseMusicale.com
    - farsi

    Quickdraw: Big Grams, Chvrches, Death Cab For Cutie, Small Black, Youth Lagoon
    - english

    video con Salmo e Noyz Narcos
    - english

    Jag Och Min Far
    - english

    stream these :: Palm + Dan Friel + Guerilla Toss + Stove + Night Birds + Swings + Wildhoney
    - english

    Angeldust, from Panorama, out on 4... – Walzerkönig. Music blog from Vienna, Austria
    - spanish

    Two Bodies (Henri Remix)
    - russian

    The Home of Great Thinkers
    - arabic

    Rhonda Smith Interview
    - norwegian

    Alps Review from Music Emissions
    - english

    All Yours [Album Review]
    - french

    SXSW 2015 - OEB Spreadsheet #48 Sunday morning...
    - russian

    Martin Castillo -(Version Official Nueva Era Music)2012 2013 video at savevid.com
    - english

    Mi destino -4CzxAQmFcd0 video at savevid.com
    - english

    filous — How Hard I Try (Robotaki Remix)
    - arabic

**Comment by mmahalwy** [comment]
Any updates on this?! I am getting this problem too and it's a huge huge problem!

**Comment by peterc** [comment]
The official advice based on experiments is now that on texts under around several words in length, you are unlikely to get reliable results, simply due to the algorithm used and the tradeoffs of using bloom filters for efficiency. We will add/change to a Unicode codepoint presence test in future (as was used in a comment above).

**Comment by sixtyfive** [comment]
So this is closed, but would it not make sense to add some sort of dictionary-based approach? One of the first examples in this issue was "How are you?" ... I just tried that as well, more than two years later, and the result has changed from `:arabic` to `:hungarian`:
```
main » wl.language "How are you?"
=> :hungarian
```

**Comment by peterc** [comment]
It does use a dictionary based approach. But because the dictionaries are heavily "compressed" using a Bloom filter, you get a certain percentage of false positives. With texts beyond a handful of words, this is no problem, but for anything very short, it does not work.

**Comment by sixtyfive** [comment]
Hmm, I get that single words would pose problems, but "how are you" is a proper sentence and not of unusual length as far as English sentences go. For the project I'm currently working on I had to choose CLD now, which is a shame because I liked whatlanguage better, API-wise.

**Comment by peterc** [comment]
CLD will definitely give you better results, but has some key downsides of its own. WhatLanguage is extremely old now (the core is about 9 years old) and does have some major limitations, which I am always quick to point out.

The latest research I've seen for doing this sort of thing in a memory efficient way is to use a combination of n-gram and codepoint histograms. I understand how this works and could reimplement it with a few days of work, but it's not time I have right now, unfortunately.

One thing that someone could do would be to have a dictionary of the X most popular words in each language and that could "reinforce" the results. That would probably take care of most shorter texts, but it would definitely be a hack.

**Comment by cmortier13** [comment]
Why not reintegrate https://github.com/peterc/whatlanguage/pull/22 ?
Because currently it's scanning only the first words until it finds a convicting language.
So if you have for ex 10 words in french followed by 1000 words in english, it will return 'french'
And also the score would be something that you can compare with number of words of the text.
