### ISSUE TITLE
Could not install with ruby 2.3.0

### ISSUE THREAD

**Issue by poudelprakash** [peterc/whatlanguage#37]
Got this error while trying to install using command:
 `$ gem install whatlanguage`

```sh
ERROR:  Error installing whatlanguage:
	invalid gem: package is corrupt, 
        exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) 
        in /home/prakash/.rvm/gems/ruby-2.3.0/cache/whatlanguage-1.0.5.gem
```

**Comment by poudelprakash** [comment]
According to [version.rb](https://github.com/peterc/whatlanguage/blob/master/lib/whatlanguage/version.rb), latest version should be `1.0.6` while `$ gem install whatlanguage` command was trying to install `1.0.5` version.

So, I tried installing from github repo directly and had a successful install.
It would be great if you guys push new version to ruby gems as mentioned in #36

**Comment by peterc** [comment]
1.0.6 has now been released.
